# Device props
MODEL_NAME="Galaxy S23 5G"
SIOP_POLICY_NAME=siop_dm1q_sm8550
CODENAME="dm1q"
VNDK="33"
STOCK_MODEL="SM-S911B"
STOCK_CSC="EUX"
STOCK_IMEI="352404911234563"

# The firmware to be used as source
MODEL="SM-S911B"
CSC="EUX"
IMEI="352404911234563"

# Extra firmware which is optional
EXTRA_MODEL=""
EXTRA_CSC=""
EXTRA_IMEI=""

# External
FILESYSTEM=erofs


# Specs
DEVICE_HAVE_SPEN_SUPPORT=false
DEVICE_HAVE_QHD_PANEL=false
DEVICE_HAVE_HIGH_REFRESH_RATE=true
SUPPORT_HAPTIC_AUDIO_VIBRATOR=true
DEVICE_HAVE_ESIM_SUPPORT=true

# Custom props (If not used , it will use values from stock rom)
#DEVICE_DISPLAY_HFR_MODE=""
#DEVICE_DISPLAY_REFRESH_RATE_VALUES_HZ=""
