# Device props
MODEL_NAME="Galaxy A22 4G"
SIOP_POLICY_NAME="siop_a22_mt6769t"
CODENAME="a22"
VNDK="31"
STOCK_MODEL="SM-A225F"
STOCK_CSC="BKD"
STOCK_IMEI="350167020473859"

# The firmware to be used as source
MODEL="SM-A155F"
CSC="AFG"
IMEI="353628426227865"

# Extra firmware which is optional
EXTRA_MODEL=""
EXTRA_CSC=""
EXTRA_IMEI=""

# External
FILESYSTEM=ext4

# Specs
DEVICE_HAVE_SPEN_SUPPORT=false
DEVICE_HAVE_QHD_PANEL=false
DEVICE_HAVE_HIGH_REFRESH_RATE=true
SUPPORT_HAPTIC_AUDIO_VIBRATOR=false
DEVICE_HAVE_ESIM_SUPPORT=false

# Custom props (If not used , it will use values from stock rom)
DEVICE_DISPLAY_HFR_MODE="2" # Supports adaptive refresh rate mode (60-90)
DEVICE_DISPLAY_REFRESH_RATE_VALUES_HZ="60,90"
IDLE_TIMER_MS=250
TOUCH_TIMER_MS=300
DISPLAY_POWER_TIMER_MS=200

