# High Performance Mode
FF "SEC_FLOATING_FEATURE_COMMON_SUPPORT_HIGH_PERFORMANCE_MODE" "TRUE"
FF "SEC_FLOATING_FEATURE_SYSTEM_SUPPORT_ENHANCED_CPU_RESPONSIVENESS" "TRUE"

# Enable Video brightness feature
FF "SEC_FLOATING_FEATURE_COMMON_SUPPORT_HDR_EFFECT" "true"

# Saiv
FF "SEC_FLOATING_FEATURE_SAIV_CONFIG_ARDOODLE_LIB" "PET_DETECTION,IMG_PICKING"
FF "SEC_FLOATING_FEATURE_GENAI_SUPPORT_TIME_WEATHER_WALLPAPER" "V2"
FF "SEC_FLOATING_FEATURE_SAIV_CONFIG_MIDAS" "UPSCALE,UPSCALE_PRO,UPSCALE_ULTRA,LOWLIGHT,HDR,DEBLUR,MOIRE,DENOISE,SHADOW,REFLECTION,UWDC,FLARE,FACERESTORATION"

# Lockscreen
FF "SEC_FLOATING_FEATURE_LOCKSCREEN_CONFIG_WALLPAPER_STYLE" "VIDEO,GENWEATHER"
