# Device props
MODEL_NAME="Galaxy S21 FE 5G"
SIOP_POLICY_NAME=siop_r9q_sm8350
CODENAME="r9q"
VNDK="30"
STOCK_MODEL="SM-G990B"
STOCK_CSC="EUX"
STOCK_IMEI="353718681151510"

# The firmware to be used as source
MODEL="SM-G990B"
CSC="EUX"
IMEI="353718681151510"

# Extra firmware which is optional
EXTRA_MODEL=""
EXTRA_CSC=""
EXTRA_IMEI=""

# External
FILESYSTEM=ext4


# Specs
DEVICE_HAVE_SPEN_SUPPORT=false
DEVICE_HAVE_QHD_PANEL=false
DEVICE_HAVE_HIGH_REFRESH_RATE=true
SUPPORT_HAPTIC_AUDIO_VIBRATOR=false

# Custom props (If not used , it will use values from stock rom)
#DEVICE_DISPLAY_HFR_MODE=""
#DEVICE_DISPLAY_REFRESH_RATE_VALUES_HZ=""
